- Correct any grammar, spelling, and punctuation errors in the text.
- Check for clarity in the text.
- Suggest improvements.
- Number each error for easy reference.
- ==Only show the lines with errors and their corrections.==
- Provide a third line explaining why each correction was made.
- Use British English dictionary
