---
feature: Pasted image 20240909161944.png
---
A key start to understand the overall Emergency Department business architecture is to start by looking at the primary value stream for people who walk in.  Depending on the location and size of the hospital, walking patients will vary from between 60% and 90% of the total number of encounters. The next largest value stream to review would be the transfer of Emergency Medical Services (EMS) patients. 

The easiest way to start the walk-in value stream analysis is to start with what in ArchiMate would be called the 'Motivation Value Stream View'. The motivation view looks primarily at the 'value' that is being provided to the person who triggers walk-in value stream. The value stream might look something like the following:

![[Emergency Room Walk-in Value Stream - Motivation View.png]]
Key to confirming that the appropriate value stages have been created is to confirm that we understand the value that is generated for the patient. In the example above, the value generated by each value stage and the overall value stream is encapsulated within the ArchiMate 'value' element. Organizationally, our hospital has developed goals (aspirational) and measures (measurable) where applicable that align to value stream stages or the overall value stream.
It is important to decide how much of the measures that have been created for the overall [[Emergency Department Measures]].