This is the text of a followup e-mail based on an initial conversation with CorryAnn Struik from In Sync Systems in Calgary on April 29, 2026.  All of these links are to content that is also contained within the Enterprise Architecture repository.

---

It was great to meet you yesterday. I am looking forward to hopefully meeting your practice lead on Friday.  I wanted to follow-up with some material following our conversation yesterday.

·        [Hospital Enterprise Domain Model](https://urldefense.proofpoint.com/v2/url?u=https-3A__stealthea.com_Stealth-2BEnterprise-2BArchitecture_Case-2BStudies_Hospital_Hospital-2BEnterprise-2BDomain-2BModel&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=Uz9oaD39Rg-L_2LEDuQY8TzMxa29fsQhXZ4s3tQ8TXdFxHL4oMPQVVdnAhpa4ySJ&m=yoeQl4JthnB-rYGRehq6Qqlr1ch6eN0D_Vys4H-JCy6DKNfC4cWLLAEV2gnbwzAL&s=lAeUAGXWZXNSuDBPHZ682WN4dRrFERQxC6bA407IgAE&e=) - This is the example that I shared with you on my iPad.

·        [Emergency Department Value Stream](https://urldefense.proofpoint.com/v2/url?u=https-3A__stealthea.com_Stealth-2BEnterprise-2BArchitecture_Case-2BStudies_Hospital_Emergency-2BDepartment_Emergency-2BDepartment-2BValue-2BStreams_Emergency-2BWalk-2Din-2BValue-2BStream-2B-2D-2BBusiness-2BCapability-2BModel&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=Uz9oaD39Rg-L_2LEDuQY8TzMxa29fsQhXZ4s3tQ8TXdFxHL4oMPQVVdnAhpa4ySJ&m=yoeQl4JthnB-rYGRehq6Qqlr1ch6eN0D_Vys4H-JCy6DKNfC4cWLLAEV2gnbwzAL&s=ziaYg5bmfGZN_TV2wkn8LqKvjCO6XzdZitSEbxSXywE&e=) - I mentioned value streams and this is an example of an ED value stream.  As you can see, a high-level

·        [Emergency Department Business Object Model](https://urldefense.proofpoint.com/v2/url?u=https-3A__stealthea.com_Stealth-2BEnterprise-2BArchitecture_Case-2BStudies_Hospital_Emergency-2BDepartment_Information-2BArchitecture_Emergency-2BDepartment-2BBusiness-2BObject-2BModel&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=Uz9oaD39Rg-L_2LEDuQY8TzMxa29fsQhXZ4s3tQ8TXdFxHL4oMPQVVdnAhpa4ySJ&m=yoeQl4JthnB-rYGRehq6Qqlr1ch6eN0D_Vys4H-JCy6DKNfC4cWLLAEV2gnbwzAL&s=lDYFwuaUzj_PJyabSyZffHvbXzT3yW95Q6i0MjH3HGs&e=) - Think of this view as a conceptual data model.  

There's a couple of other things that may be relevant for the assignment you're thinking about:

1.  [Closed Loop Analytics](https://urldefense.proofpoint.com/v2/url?u=https-3A__stealthea.com_Stealth-2BEnterprise-2BArchitecture_Enterprise-2BArchitecture_Information-2BArchitecture_Closed-2BLoop-2BAnalytics&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=Uz9oaD39Rg-L_2LEDuQY8TzMxa29fsQhXZ4s3tQ8TXdFxHL4oMPQVVdnAhpa4ySJ&m=yoeQl4JthnB-rYGRehq6Qqlr1ch6eN0D_Vys4H-JCy6DKNfC4cWLLAEV2gnbwzAL&s=Xp0OylBLxOi9aJaXcxa6vtDJgdWsPbogaIW80k7gcK8&e=) - I am planning to go deeper into this topic once my [Revv52 performance](https://urldefense.proofpoint.com/v2/url?u=https-3A__revv52.com_event_classicalcollision_&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=Uz9oaD39Rg-L_2LEDuQY8TzMxa29fsQhXZ4s3tQ8TXdFxHL4oMPQVVdnAhpa4ySJ&m=yoeQl4JthnB-rYGRehq6Qqlr1ch6eN0D_Vys4H-JCy6DKNfC4cWLLAEV2gnbwzAL&s=5t4XgH_X9yBRX-xOIylcC7gLckPy3Cw2uaSf_X4P7PU&e=) is over next weekend. This does provide a high-level overview of what my concept is for building out a data pipeline to support enterprise analytics.

2.  [The AI Paradox](https://urldefense.proofpoint.com/v2/url?u=https-3A__stealthea.substack.com_p_the-2Dai-2Deconomic-2Dparadox&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=Uz9oaD39Rg-L_2LEDuQY8TzMxa29fsQhXZ4s3tQ8TXdFxHL4oMPQVVdnAhpa4ySJ&m=yoeQl4JthnB-rYGRehq6Qqlr1ch6eN0D_Vys4H-JCy6DKNfC4cWLLAEV2gnbwzAL&s=uwULpfB-hIcJauZUoHNPrafkJYskCrnSAZsgZwi91W4&e=) - This is one of my first Substack posts and I got some good initial traction.  I review the economics of AI - at least what we can see from looking in from the outside of large private organizations.  I am a huge proponent of organizations investing in open source models even if they choose to support any of the foundation models.

Please let me know if you have any questions.