# Epic Willow VIMS Capability Assessment Matrix — Initial Proposed Responses

**Date:** June 9, 2026 (updated June 11, 2026 — external on-hand capture premise; portal scope expansion)
**Purpose:** Pre-populated draft of the [[Epic Willow Inventory Assessment Package]] Section 3 capability matrix. The four previously blank columns (response category, proposed approach, complexity, assumptions/dependencies) are filled in as the **Province's working hypotheses**, derived from the [[Epic Willow Gap Assessment - Alberta Instance Extension]], the [[SBAR - Epic Willow Extension for Provincial Vaccine Depot]], and the two supplied Epic guides (X12 Interface Setup Guide, May 2, 2025; Pharmacy Inventory Management Setup and Support Guide, May 1, 2026).

> **Important framing:** The capability matrix is ultimately Epic's to complete and confirm. These entries are an *initial proposed response* intended to (a) seed Epic's formal response, (b) flag where the Province already has a defensible position from the analysis, and (c) isolate the rows that genuinely require Epic confirmation. Entries marked **⚠ Confirm with Epic** are dependencies the analysis could not resolve from the documents alone.

---

## Response & Complexity Legend

**Response category** (per the assessment package definitions):
Native · Configuration · Custom Development · Third-Party · Not Supported

**Complexity / effort:** Low (<40h) · Medium (40–200h) · High (>200h) · Major Enhancement (product development / major extension)

**Split rating (added June 11, 2026):** where the portal scope expansion applies, complexity is shown as **Epic:** (Connect Care config/build effort) **· Portal:** (custom portal build effort). This keeps the Epic-facing response clean while still tracking total solution effort. Portal-side ratings assume a shared portal platform (authentication, site registry, notification engine, batch sync) built once and amortized across rows.

**Architecture premise carried from the Gap Assessment:** internal users (PVD, 13 regional depots, Public Health sites) operate on Connect Care HyperDrive directly; community pharmacies and physician clinics reach Willow through a **custom web portal** that authenticates against Epic provider-portal credentials and submits orders via **GHX XML batch import (Batch Scheduler template 48016)** as the primary path, with Interconnect/FHIR reserved for status reads and urgent orders. Vaccines are assumed to be built as **medications** (improving the FHIR read/catalog surface). *(Portal scope expanded June 11, 2026 — see portal scope expansion premise below.)*

**Location-model confirmation (June 11, 2026):** it is confirmed that Willow Inventory locations require **no linkage to Epic Departments or Facilities**. Community pharmacy, physician, and any external non-Epic location can be created as inventory locations with no real limitations. The multi-organization inventory model gap is **resolved** and removed from the Gap Assessment; remaining work is security/reporting configuration, not architecture.

**Scaling assumption (updated June 9, 2026):** the existing Connect Care instance is provisioned for ~100,000 users; adding the VIMS user population (≈5,000 named / 500–1,000 concurrent per AD-07) is treated as a marginal load that **does not impact clinical operations**. Raw infrastructure capacity is therefore **no longer treated as an open risk**. The remaining throughput consideration is narrower: the batch-import/portal path and any peak external ordering surge, not the Epic instance itself.

**External on-hand capture premise (added June 11, 2026):** community providers (pharmacies, physician clinics) report current on-hand inventory **through the portal**, and the portal back end **re-purposes Willow's ADS (medication cabinet) load/unload interface** to post those counts as HL7 ZPM messages against the corresponding external Willow inventory locations. Per the Pharmacy Inventory Management Guide ("Turn on Automatic Inventory Tracking for ADS Pharmacies," pp. 84–86): the system auto-creates inventory locations, items, and balances from inbound messages; balances are updated from ZPM-11 (delta) / ZPM-16 (total count); par/optimum/maximum levels are maintained from ZPM-22/ZPM-23. Consequences:

- External on-hand becomes **native Willow balance data** — Cogito/SlicerDicer report external sites like internal ones; no separate external-visibility data store.
- The **portal is the single aggregation point**: one consolidated inbound interface, not ~1,500 point feeds from heterogeneous pharmacy systems. Physician clinics without dispensing software are covered by manual portal counts.
- Pairing with **inventory hold locations** (PIM Guide pp. 31–32) — each depot designated as hold location for its sites — means a site's receipt-time "load" message auto-transfers stock depot→site, providing **native receipt confirmation** (closes the A4 post-ship gap created by imported requests closing on ship, p. 156).
- Count messages (ZPM-16 total-in-pocket semantics) double as **remote cycle counts**, replacing the missing external reconciliation path.

⚠ Confirm with Epic: (a) supportability/licensing of the ADS load/unload interface with a **non-ADS message source** (portal back end emulating a cabinet); (b) **lot/expiry granularity** carried in ZPM messages — gates the B2/D3/A7/D5 upgrades; (c) whether hold-location auto-transfer behaviour applies when the "ADS" is an emulated external location.

**Portal scope expansion (added June 11, 2026):** the custom web portal is elevated from external order entry + on-hand capture to the **front-end application for the larger Epic gaps at all non-Epic locations**. The portal syncs with Willow through the already-defined paths — GHX XML batch import (template 48016), the ADS ZPM feed, Interconnect/FHIR reads, and Cogito extracts — and accepts **batch file uploads** (e.g., from pharmacy dispensing systems) where direct interfaces are impractical. The portal is also the **single notification application for non-Epic inventory locations**: shipment, low-stock, near-expiry, recall, and account-event notifications to external sites are issued from the portal's notification engine, not from Epic. Functions absorbed by the portal:

- **Tier-based ordering rules & product-list eligibility** (A2) — enforced at portal order entry.
- **Order approval queueing** (C2) — external orders held in the portal for depot/program review *before* batch import; Willow only ever receives approved orders.
- **Variance thresholds & exception justification** (C5/C6) — threshold checks against Willow pars/on-hand at order entry; reason codes captured in the portal and preserved for audit.
- **Recall execution** (A7/D5) — multi-site notification, acknowledgement tracking, freeze-at-order-entry (recalled lots blocked from ordering), return tracking, completion reporting. Identification stays native in Cogito.
- **Redistribution pull-back** (A8) — pull-back instructions and return tracking issued through the portal.
- **Guided external returns & cold-chain incident capture** (A6/B8) — portal forms for external sites; results posted to Willow via the established feeds.
- **Post-ship / receipt status** (C3) — the portal owns provider-facing status after import, covering the imported-requests-close-on-ship limitation (PIM Guide p. 156).

Net effect: Epic-side custom development shrinks materially — most "Custom Development" rows become Epic configuration plus a portal module — and the recall gap drops from Major Enhancement to a portal build. The trade is **concentration risk**: one custom application now carries many requirements (see new Section 5 gap). ⚠ Confirm with Epic: outbound event/extract mechanism (push vs scheduled extract vs Interconnect polling) to feed the portal notification engine.

---

## A — Provincial Warehouse & Distribution

| ID | Requirement | Proposed response | Proposed approach | Complexity | Assumptions / dependencies / reference sites |
|----|-------------|-------------------|-------------------|------------|----------------------------------------------|
| A1 | Provincial warehouse inventory management | **Native / Configuration** | Willow's core warehouse functions — receive, store, allocate, pick, pack, ship, adjust, report — are native. Provincial-scale configuration of the PVD as a central inventory location within Connect Care. | Medium | Confirmed-capability per Gap Assessment "Low/No Gap" list. PVD modelled as a Willow inventory location/facility. |
| A2 | Multi-tier distribution model | **Configuration + Custom Development** | Three-tier hierarchy (PVD → 13 depots → providers) modelled via Willow inventory locations — confirmed to require no Epic Department/Facility linkage, so depot and external (pharmacy/physician) locations can be created without limitation — plus internal-supplier configuration for Tiers 1–2; tier-specific ordering rules and product-list eligibility for external tiers **enforced at portal order entry** (portal scope expansion, June 11, 2026) — only internal-tier visibility/security remains Epic-side. | Epic: Medium · Portal: Medium–High | Location-model confirmation (June 11, 2026); Gap Assessment §1. Internal tiers simplified by single Connect Care instance; external tier rules live in the portal. |
| A3 | Depot-to-depot transfers | **Configuration** | Native Willow Direct Transfer (two-step) and Internal Purchase Request workflows preserve lot, expiry, quantity, shipment, receipt, and audit history. Configure PVD/depots as internal suppliers with purchase contracts. | Medium | Pharmacy Inventory Guide confirms transfer mechanisms. "Allow direct transfers" + receiving-location config required. |
| A4 | Depot-to-provider distribution | **Configuration (internal) + Custom Development (external)** | Public Health sites: native HyperDrive internal requests. Pharmacies/clinics: portal generates GHX XML → batch 48016 import → appears on depot "Requests to Fulfill" tab → pick/pack/ship. **Receipt confirmation now native (June 11, 2026):** site confirms receipt in portal → portal emits ADS "load" message → hold-location auto-transfer depot→site (PIM Guide pp. 31–32, 84–86). Portal is the shared external front end (portal scope expansion). | Epic: Medium · Portal: High | ⚠ Confirm with Epic: GHX XML schema, min. job interval (template 48016, parent SLG 3992958); hold-location auto-transfer with emulated ADS source. |
| A5 | Inventory receiving | **Native** | Receive product with product/lot/expiry/quantity/holding-location capture. X12 856 ASN can auto-create and auto-receive shipments (`CREATE_SHIPMENT`, `AUTO_RECEIVE`). | Low | X12 Guide confirms inbound 855/856/810 + auto-balance creation (`CREATE_BALS_FOR_UNSTOCKED_ITEMS`). |
| A6 | Inventory returns | **Configuration + Custom Development (internal) / Portal (external)** | Return-to-depot/PVD with configurable reason codes is native; *guided* prompts (cold-chain form attachment, product-problem form) and viable/non-viable separation per SR-16: **external sites use portal guided-return forms** (portal scope expansion, June 11, 2026), posted to Willow via established feeds; internal prompts remain an Epic workflow build. | Epic: Low–Medium · Portal: Low–Medium | Reason codes native; internal forced-documentation prompts custom (see B8); external prompts in portal. |
| A7 | Recall management | **Configuration (identification) + Portal (recall execution)** | Lot-level identification native internally — and **extends to external sites** where portal-reported counts carry lot (external on-hand premise), making affected-site/lot identification a native Cogito report. **Recall execution moves to the portal** (portal scope expansion, June 11, 2026): multi-site notification via the portal notification engine (it already holds the site registry/contacts), acknowledgement tracking, freeze-at-order-entry (recalled lots blocked from portal ordering), return tracking, and completion reporting. | Epic: Low–Medium · Portal: High | **Re-assessed June 11, 2026: down from Major Enhancement** — recall becomes a portal module over native identification, not an Epic product extension. Gap Assessment §3. ⚠ Lot granularity in ZPM messages gates external identification; ⚠ confirm no Epic module already covers provincial supply-chain recall. |
| A8 | Redistribution during shortages | **Configuration (visibility) + Custom Development (external action)** | Internal near-expiry identification + Rebalance Stock activity (available Feb 2026) generates suggested transfers — native for PVD/depots. **External visibility now native** (June 11, 2026): portal→ADS feed makes external balances visible to Rebalance Stock / near-expiry reporting. The pull-back *action* — instructing and tracking returns from external providers — runs through the **portal notification engine + guided-return forms** (portal scope expansion, June 11, 2026). | Epic: Low–Medium · Portal: Medium | Gap Assessment §4. Rebalance Stock confirmed in Pharmacy Inventory Guide. ⚠ Confirm Rebalance Stock scopes across external inventory locations. |
| A9 | Emergency response inventory management | **Configuration** | Achievable through Willow allocation/transfer + reporting. Instance capacity is no longer a constraint (see scaling assumption); effort is the workflow/reporting build, not infrastructure. | High | Infra risk retired by scaling assumption. Functional build still required. |
| A10 | Pandemic response inventory management | **Configuration** | Same workflow basis as A9 at higher volume. Raw instance scaling is no longer the limiter; the open question narrows to batch-import/portal throughput during a provider ordering surge, plus the (custom) redistribution and bulk-ordering builds. | High | Depends on portal/batch path capacity (A4, C1, C10), not Epic instance sizing. |

---

## B — Inventory Core

| ID | Requirement | Proposed response | Proposed approach | Complexity | Assumptions / dependencies / reference sites |
|----|-------------|-------------------|-------------------|------------|----------------------------------------------|
| B1 | Lot tracking | **Native** | Willow tracks inventory by lot at every holding location, persisting across receiving, transfers, ordering, returns, wastage, recall. | Low | Confirmed-capability list. |
| B2 | Expiry tracking | **Native (internal) / Configuration (cross-tier, conditional)** ⚠ | Expiry dates and near-expiry alerts native within an organization. Cross-tier aggregation for external sites becomes native reporting under the external on-hand premise, **provided** portal capture includes lot/expiry and the ADS interface persists it to external balances. | Low (internal) / Medium (external) | Gap Assessment §4. ⚠ Confirm lot/expiry support in ZPM messages (June 11, 2026 premise). |
| B3 | Batch management | **Custom Development** | No general-purpose batch intake pipeline with error queues, retries, and operational monitoring. GHX template 48016 covers external order import only; bulk vaccine/transfer data loads with validation dashboards must be built. | High | Gap Assessment §6. Epic ETL tools are not provider-facing/operational. |
| B4 | Product master management | **Native / Configuration** | Vaccine product master maintained natively; building vaccines as **medications** (INR formulary records) aligns DIN/RxNorm identification and exposes mature FHIR `Medication`/`MedicationKnowledge` resources. | Medium | Decision dependency: vaccines-as-medications build (Gap Assessment, FHIR section). |
| B5 | Inventory adjustments | **Native** | On-hand increase/decrease with configurable reason codes and preserved audit history (SR-19). | Low | Confirmed-capability list. |
| B6 | Inventory reconciliation | **Native** | Physical counts, count sheets, reconciliation reports, discrepancy resolution within a facility (RNA-03). | Low | Confirmed-capability list. |
| B7 | Wastage tracking | **Native** | Wastage in doses by product, location, reason code, tier (within instance). | Low | Confirmed-capability list; reporting breakdown by tier via Cogito (see D4). |
| B8 | Cold chain incident management | **Configuration + Custom Development (internal) / Portal (external)** | Reason codes and wastage-with-cause native; the guided incident workflow (branching prompts, forced documentation, auto-flagging, supervisory notification) requires custom build internally. **External sites capture incidents through portal guided forms** (portal scope expansion, June 11, 2026), with results posted to Willow via established feeds and supervisory notification via the portal engine. | Epic: Medium · Portal: Low–Medium | Gap Assessment §5. |
| B9 | Multi-location storage | **Native** | Fridge/cart/shelf/depot holding points configurable within a facility (SR-09, SR-10). | Low | Confirmed-capability list. |
| B10 | Holding point management | **Native** | Restrict pick locations and display holding points on picking/packing slips. | Low | Confirmed-capability list (SR-09). |

---

## C — Ordering & Distribution Workflow

| ID | Requirement | Proposed response | Proposed approach | Complexity | Assumptions / dependencies / reference sites |
|----|-------------|-------------------|-------------------|------------|----------------------------------------------|
| C1 | Provider ordering | **Configuration (internal) + Portal (external)** | Public Health: native internal requests on HyperDrive. Pharmacies/clinics: portal → GHX XML batch 48016 (routine) / Interconnect (urgent). Ordering UI is part of the core portal build (portal scope expansion). | Epic: Medium · Portal: High | ⚠ Confirm 48016 schema + Interconnect urgent-order endpoint. |
| C2 | Order approval workflows | **Portal (pre-import approval) / Configuration (fallback)** | **Re-assessed June 11, 2026:** external orders are held in a **portal approval queue before batch import** — depot/program reviewers approve/reject/adjust with variance flags; Willow only receives approved orders, so no Epic-side approval build. Fallback/alternative: Inventory Workqueue Blocking Rules + Immediate Sign Off (PIM Guide pp. 135–136) if Epic-side gating is preferred. | Epic: Low · Portal: Medium–High | Gap Assessment §2 — Epic-side custom development eliminated by pre-import approval. Internal (depot↔PVD) approvals, if required, still need Epic workqueue config. |
| C3 | Order status tracking | **Configuration (internal) + Portal (external)** ⚠ | Internal: native via "Requests to Fulfill" / request lifecycle. External: portal surfaces in-Willow lifecycle via Interconnect reads **and owns post-ship/receipt status from its own events** (imported requests close on ship, PIM Guide p. 156 — the portal covers the gap Willow cannot). | Epic: Low · Portal: Medium | ⚠ Confirm Interconnect order-status-by-ID read endpoint. |
| C4 | Shipment tracking | **Native / Configuration + Portal (external alert)** ⚠ | Outbound shipment tracking native with configuration (SR-15). "Vaccine shipped" alert to external recipients issued by the **portal notification engine** (shared build — see C7), fed by a Willow shipment event/extract. | Epic: Low–Medium · Portal: Low (shared engine) | ⚠ Confirm outbound event/extract mechanism (push/poll) from Willow — see Open Confirmation Item 14. |
| C5 | Variance thresholds | **Configuration + Portal (enforcement)** | Par-level configuration approximates thresholds — grounded in **actual reported on-hand** since ZPM-22/23 maintain par/optimum/maximum on external balances (June 11, 2026 premise). **Threshold enforcement moves to portal order entry** (portal scope expansion): usage-/schedule-based variance logic checks each external order against Willow pars/on-hand before submission (SR-13). No Epic-side variance build. | Epic: Low–Medium · Portal: Medium | Gap Assessment §1; external on-hand premise. Portal needs on-hand/par read (see C8 ⚠). |
| C6 | Exception justification | **Portal** | Configurable reason-code capture on out-of-threshold orders at **portal order entry**, preserved in the portal (and carried on the imported order where the GHX schema allows) for review/approval/reporting/audit (SR-14). | Epic: Low · Portal: Medium | Gap Assessment §1 — **re-assessed June 11, 2026:** Epic-side custom build eliminated; capture happens before import. ⚠ Confirm whether 48016 GHX XML carries free-text/reason fields. |
| C7 | Automated notifications | **Configuration (internal) + Portal (external — single notification application)** | Internal via Epic in-system/email. **All external notifications consolidated in the portal notification engine** (portal scope expansion, June 11, 2026): shipment (C4), low stock, near expiry, recall (A7), pull-back (A8), program-admin email (SR-20/SR-21), new-user/password emails. One shared engine serves all rows. | Epic: Low–Medium · Portal: Medium (shared engine, built once) | RNA-04, SR-15, SR-20, SR-21. ⚠ Event/extract feed from Willow/Cogito to drive triggers (Open Confirmation Item 14). |
| C8 | Inventory-driven ordering | **Configuration (internal + external data) + Custom Development (portal display)** | On-hand display, minimum increments, ordering schedule native internally (SR-11). **External on-hand now exists as native Willow balances** (June 11, 2026 premise) — and since ZPM-22/23 maintain pars, Willow's replenishment logic can generate **system-suggested resupply** for external sites, shifting routine ordering from provider-push toward par-driven replenishment. Portal display of Willow-side balance and suggested-resupply surfacing need an Interconnect/extract read. | Epic: Low–Medium · Portal: Low–Medium | ⚠ Confirm on-hand-by-location read for portal (narrowed — display only, no longer the data source). Read also feeds C5 threshold checks. |
| C9 | Forecast-based ordering | **Third-Party / Not Supported (native)** | No native demand forecasting or AI allocation. Requires third-party forecasting tool integrated to Willow data, or manual process. | Major Enhancement | Gap Assessment §10. Desirable, not mandatory. |
| C10 | Bulk ordering | **Configuration** | High-volume/seasonal ordering via internal request workflow and batch import; load-tied to A9/A10 scaling question. | Medium | Depends on infra confirmation for peak periods. |

---

## D — Reporting & Analytics

| ID | Requirement | Proposed response | Proposed approach | Complexity | Assumptions / dependencies / reference sites |
|----|-------------|-------------------|-------------------|------------|----------------------------------------------|
| D1 | Real-time inventory visibility | **Configuration + Interface (external via portal→ADS feed)** | Near-real-time across PVD/depots via Cogito/Workbench. **External sites now report on-hand through the portal, posted to native Willow balances via the ADS interface** (June 11, 2026 premise) — Cogito reports external locations like internal ones; no separate visibility layer. | Medium | External data freshness = provider reporting cadence through the portal, not a technical limit. Gap Assessment §5 external-visibility gap substantially resolved. |
| D2 | Provincial inventory dashboard | **Configuration** | Cogito / Radar dashboards and SlicerDicer for inventory by product, lot, region, depot, funding type, expiry horizon. | Medium–High | Requires Cogito reporting build; ⚠ confirm Cogito licensing in scope. |
| D3 | Near-expiry reporting | **Native / Configuration** | Near-expiry reporting native within instance; external-site coverage now extends via portal-reported counts **if lot/expiry is captured** (June 11, 2026 premise). | Medium | RNA-01/RNA-04. ⚠ Lot/expiry in ZPM feed. |
| D4 | Wastage reporting | **Configuration** | Wastage by product/location/reason/tier/period via Cogito; export to CSV/PDF/Excel. | Medium | SR-12, RNA-01. |
| D5 | Recall reporting | **Configuration (identification) + Portal (workflow reporting)** | Affected-location/quantity/lot identification becomes native Cogito reporting over external balances (lot-dependent, June 11, 2026 premise). Return-progress/acknowledgement/completion reporting comes from the **portal recall module** (A7) — the portal holds the execution data. | Epic: Medium · Portal: (within A7 module) | Tied to A7. ⚠ Lot granularity in ZPM feed. |
| D6 | Ordering trends | **Configuration** | Ordering/usage trends by tier/product/location/provider group/period via Cogito. | Medium | RNA-01. |
| D7 | Utilization trends | **Configuration** | Movement/use/wastage/ordering pattern analysis via Cogito. | Medium | Project objectives; RNA-01. |
| D8 | Forecasting | **Third-Party** | Forecasting/demand anticipation not native; integrate external analytics/forecasting tool. | Major Enhancement | Gap Assessment §10. |
| D9 | Demand planning | **Third-Party / Configuration (limited)** | Cogito supports historical analysis; predictive demand planning across routine/seasonal/outbreak/pandemic likely external. | Major Enhancement | ⚠ Confirm Cogito predictive scope vs external tool. |
| D10 | Pandemic inventory modelling | **Third-Party / Custom Development** | Supply/demand/allocation scenario modelling and surge distribution require external analytics or custom modelling. | Major Enhancement | Project objectives. |

---

## E — Barcode & Automated Identification

| ID | Requirement | Proposed response | Proposed approach | Complexity | Assumptions / dependencies / reference sites |
|----|-------------|-------------------|-------------------|------------|----------------------------------------------|
| E1 | GS1 Data Matrix | **Configuration** | Willow supports barcode-scanning input; configure GS1 Data Matrix parsing for vaccine product identification. | Medium | SR-05 allows 12-month delivery window; pre-RFP roadmap evidence needed. |
| E2 | WHO AIVP compliance | **Configuration** | Align scanning to WHO AIVP; build DIN/GTIN ↔ internal item crosswalk (X12 guide references NDC — Canadian DIN mapping required). | Medium | X12 Guide Canada note; engage Epic Canadian EDI team. |
| E3 | Barcode receiving | **Native / Configuration** | Scan during receiving to populate product/manufacturer/lot/expiry. | Medium | E1/E2 parsing prerequisite. |
| E4 | Barcode picking | **Configuration** | Scan-verify product/lot/quantity/holding location during fulfillment. | Medium | Aligns with picking/packing (SR-09). |
| E5 | Barcode inventory counts | **Configuration** | Barcode-assisted counts/reconciliation. | Medium | Supports RNA-03. |
| E6 | Automated lot capture | **Configuration** | Parse lot from GS1 barcode into inventory record. | Medium | Depends on GS1 parsing build. |
| E7 | Automated expiry capture | **Configuration** | Parse expiry from GS1 barcode for expiry/near-expiry/recall use. | Medium | Depends on GS1 parsing build. |

---

## F — Integration & Interoperability

| ID | Requirement | Proposed response | Proposed approach | Complexity | Assumptions / dependencies / reference sites |
|----|-------------|-------------------|-------------------|------------|----------------------------------------------|
| F1 | REST APIs | **Native** | Epic FHIR R4 and Interconnect expose REST APIs for integration/automation/data exchange. | Medium | AD-09/AD-11/AD-12. Write-side supply operations still need confirmation (see F4). |
| F2 | HL7 v2 | **Native** | HL7 v2 inbound/outbound/bidirectional via Epic Bridges (MLP over TCP/IP). | Medium | AD-10, SR-01. Identify any Z-segment deviations. |
| F3 | HL7 v3 | **Configuration** | HL7 v3 supported where needed for provincial HIE patterns. | Medium | AD-10; scope-dependent. |
| F4 | FHIR | **Native (read) / ⚠ Confirm (write)** | Mature FHIR on medication domain (`Medication`, `MedicationKnowledge`, `MedicationRequest`, `MedicationDispense`). Supply chain — `SupplyRequest`/`SupplyDelivery` **write** to Willow is the key open item; `SupplyRequest.item` can reference a `Medication`. | Medium | ⚠ Confirm Epic support for SupplyRequest/SupplyDelivery writes (Gap Assessment, FHIR section). MedicationRequest cannot model bulk requisitions (no patient context). |
| F5 | CSV import/export | **Native / Configuration** | Standard CSV/SQL/tab-delimited import/export for admin users (SR-17); reporting export native via Cogito. | Low–Medium | AD-09, SR-17. |
| F6 | SFTP | **Native / Configuration** | Secure file transfer for batch feeds; aligns with GHX XML deposit/import (template 48016). | Low–Medium | AD-09. |
| F7 | Provincial immunization repository integration | **Configuration / Custom Development** | Integrate to Alberta immunization registry while preserving inventory-vs-clinical distinction. | High | AD-12, SR-01; interface design required. |
| F8 | Connect Care integration | **Native** | VIMS lives *within* the Connect Care instance — no external interface for internal tiers. | Low | Core architecture premise (SBAR). |
| F9 | Netcare integration | **Custom Development** | Inventory-related data exchange with Netcare (primarily clinical infrastructure) requires interface build if in scope. | Medium–High | AD-12; scope to confirm. |
| F10 | Pharmacy system integration | **Custom Development** | Independent pharmacy systems (Kroll/PharmaClik) exchange order/shipment/inventory data without becoming Epic clinical sites — via the portal + batch/Interconnect; DIN-based product identification aligns with medication build. **Inventory updates now have a documented Epic-side mechanism:** portal back end → ADS load/unload interface (June 11, 2026 premise) — the custom surface is portal capture/translation, not a bespoke Epic interface. Pharmacy systems without interface capability use **batch file uploads to the portal** (portal scope expansion). | Epic: Low–Medium · Portal: Medium–High | AD-09/AD-12/SR-01; Gap Assessment FHIR/X12 sections; PIM Guide pp. 84–86. |

---

## G — Security, Hosting & Compliance

| ID | Requirement | Proposed response | Proposed approach | Complexity | Assumptions / dependencies / reference sites |
|----|-------------|-------------------|-------------------|------------|----------------------------------------------|
| G1 | Role-based access control | **Native / Configuration** | Epic security classes/templates restrict ordering, edit, delete, visibility, and facility access by role/tier/facility; Tier-3 multi-facility dropdown (SR-18). | Medium | SR-04, PS1–PS5. External pharmacy isolation via EAF-scoped portal identities. |
| G2 | Multi-factor authentication | **Native / Configuration** | Epic + portal MFA; federation/SSO (SAML/OIDC/OAuth2) for external users. | Low | PS7, PS10. |
| G3 | Audit logging | **Native** | Epic captures user activity, config/privilege changes, inventory/order actions; admin audit reporting (PLAS-aligned). | Low | PS13–PS15B, PLAS 2.0. |
| G4 | Canadian hosting | **Native** ✅ | Connect Care is an HSS-hosted Epic instance running in Alberta data centres — Canadian hosting requirement met. | Low | Resolved June 11, 2026 (AD-03, PS43). |
| G5 | Data residency | **Native** ✅ | HSS self-hosting in Alberta data centres keeps storage/processing/backup/recovery/network within Canada. | Low | Resolved June 11, 2026 (POPA/HIA, PS43). |
| G6 | Encryption at rest | **Native** | Cryptographic protection of data and backups with key management. | Low | PS11, PS26 (SC-13). |
| G7 | Encryption in transit | **Native** | TLS/SSH transport protection. | Low | PS12 (SC-8). |
| G8 | Disaster recovery | **Native / Configuration** | HSS-hosted DR (Alberta data centres) with documented plan, annual testing, RTO≤24h. | Medium | Schedule C, PS25/PS26; Canadian DR facility resolved June 11, 2026 via HSS Alberta hosting (G4/G5); confirm DR plan documentation and test cadence. |
| G9 | Business continuity | **Native / Configuration** | BCP, backups, incident management, recovery (CP-2/CP-9/CP-10). | Medium | Schedule C, OP-01, PS25. |
| G10 | HIA compliance support | **Configuration + Governance** | HIA/POPA/ATIA privacy controls, safeguards, auditability, breach response, RBAC. Multi-organization data ownership needs legal review. | High | Legal/governance design needed; technical location-model gap resolved June 11, 2026 (no Department/Facility linkage required). |

---

## UX & Operational Groups

| ID | Requirement | Proposed response | Proposed approach | Complexity | Assumptions / dependencies / reference sites |
|----|-------------|-------------------|-------------------|------------|----------------------------------------------|
| UX1 | SaaS cloud web-based frontend | **Native (internal) + Custom Development (external)** | HyperDrive is web-based for internal users; community providers use the custom web portal (browser-only, minimal requirements). | Medium | UE-01, AD-06. |
| UX2 | Responsive UI & GoA/PPHS accessibility | **Not Supported (core Willow) / Custom Development (portal)** | Epic's standard Willow UI was not designed to GoA/PPHS UI-UX/WCAG standards and cannot be reskinned; the custom external portal can be built to standard. | High (portal) | Gap Assessment §8 — **compliance gap for the Epic UI.** |
| UX3 | Self-help & online education | **Native / Configuration** | Epic in-app help, training materials, role-based content; portal help built to standard. | Medium | UE-05/06/07, Appendix B. |
| OPS1 | Multiple environments | **Native / Configuration** | Epic provides POC/non-production environments (prod, UAT, sandbox, training) with DB access. | Medium | AD-02; confirm 4-environment + DB-access provisioning model. |
| OPS2 | Scalability (5,000 named / 500–1,000 concurrent) | **Native / Configuration** | The existing instance is provisioned for ~100,000 users; the VIMS population is a marginal addition well within capacity. | Low | Scaling assumption (June 9, 2026); AD-07. Confirm licensing for added named users. |
| OPS3 | Availability & reliability | **Native / Configuration** | 24/7 availability, fault tolerance, maintenance windows, SLAs per HSS hosting of the Alberta Epic instance. | Medium | AD-08, Schedule A; confirm HSS Alberta data centres meet Tier II+ (OP-03). |
| OPS4 | Service desk support (~5,000 users) | **Configuration / Services** | Defined service desk, ticketing, 15-min call response, escalation (OP-06). | Medium | OP-02/OP-06, Schedule A; commercial/staffing model. |
| OPS5 | Training & change management | **Services / Configuration** | Role-based training, external-provider training, train-the-trainer, readiness/adoption. | Medium | Appendix B, Attachment #4. |
| OPS6 | Transition & data migration | **Custom Development / Services** | Migrate from existing VIMS, map/validate/reconcile data, cutover, parallel run. | High | Appendix B, Schedule D; historical-data approach to define. |
| OPS7 | Service levels & reporting | **Configuration / Contractual** | Bi-weekly project + monthly SLA reporting (outages, integrity, incidents, UAT defects, abandonment). | Medium | RFP 3.2, Schedule A. |
| OPS8 | Security controls & SDLC | **Native (Epic posture)** | NIST 800-53-informed controls across access, encryption, logging, IR, vuln mgmt, pen testing, SDLC, change mgmt. | Medium | PS1–PS43; map Epic attestations (e.g., HITRUST/SOC2) to PS controls. |

---

## Section 5 — Gap Analysis (populated)

| Gap | Requirement impacted | Business impact | Proposed workaround | Estimated effort | Residual risk |
|-----|----------------------|-----------------|---------------------|------------------|---------------|
| Inbound requisitions from external pharmacies/clinics | C1, A4, SR-02 | Tier-3 ordering cannot occur natively; core distribution flow blocked. Imported requests **close when all items ship** (PIM Guide p. 156) — but receipt confirmation is **now native** (June 11, 2026): portal receipt event → ADS "load" message → hold-location auto-transfer depot→site (pp. 31–32) | Custom portal → GHX XML batch import (template 48016, PIM Guide pp. 156–159; Epic engagement via SLG 3992958); Interconnect for urgent/status; portal→ADS feed for receipt + on-hand | Epic: Medium · Portal: High | **Medium** — import pattern verified in primary Epic documentation; outstanding: batch interval, volume at ~1,500 sites, workqueue gating of imported requests |
| ~~Multi-organization inventory & data separation~~ (resolved) | A2, G1, G10 | *Resolved June 11, 2026 — Willow Inventory locations require no Epic Department/Facility linkage; external non-Epic locations can be created with no real limitations* | N/A — removed from Gap Assessment | None | **Closed.** Residual is security configuration (per-location visibility scoping) + legal/governance review of data ownership, not an architectural gap |
| Province-wide recall management | A7, D5, SR-16 | Cannot reliably notify/freeze/return recalled lots across ~1,500 sites. **Identification half mitigated June 11, 2026:** external balances (with lot, if confirmed) make affected-site/lot identification a native report. **Execution half re-assessed (portal scope expansion):** portal recall module handles notification, acknowledgement, freeze-at-order-entry, return tracking, completion reporting | Portal recall module over native Cogito identification — no Epic product extension required | Epic: Low–Medium · Portal: High (down from Major Enhancement) | **Medium** — both halves now have a defined home; conditional on lot in the portal→ADS feed and portal delivery |
| Order approval routing & status tracking (narrowed June 11, 2026; verified vs. PIM Guide May 2026) | C2, C3 | Native status lifecycle documented (Draft→Submitted→Shipped→Received→Closed; picking is an activity, not a status — PIM Guide pp. 125, 140, 156). Native approval candidate: Inventory Workqueue **Blocking Rules** + Immediate Sign Off (pp. 135–136) | **Primary (portal scope expansion, June 11, 2026): portal pre-import approval queue** — Willow only receives approved orders, eliminating the Epic-side approval build. Fallback: Workqueue Blocking Rules if they apply to imported Requests-to-Fulfill (confirm with Epic TS). Provider-facing status via portal — imported requests close on ship (p. 156), so the portal owns post-ship status from its own events | Epic: Low · Portal: Medium–High | **Low–Medium** — pre-import approval removes the dependency on Epic workqueue confirmation; residual is portal delivery |
| Tier-based ordering rules & variance thresholds | C5, C6, A2 | Eligibility/threshold enforcement and exception capture absent | **Portal order-entry enforcement** (portal scope expansion, June 11, 2026): eligibility rules, threshold checks against Willow pars/on-hand, reason-code capture — all before import. Epic side reduced to par configuration | Epic: Low–Medium · Portal: Medium–High | **Low–Medium** — enforcement point well-defined; depends on on-hand/par read (C8 ⚠) and portal delivery |
| Redistribution workflow for external providers | A8 | Cannot pull near-expiry stock back from external sites. **Visibility side resolved June 11, 2026** — external balances native via portal→ADS feed | Internal: Rebalance Stock (Feb 2026), potentially scoped across external locations (⚠ confirm). External pull-back action: **portal notification engine + guided-return forms** (portal scope expansion) | Epic: Low–Medium · Portal: Medium | **Low–Medium** — both visibility and action now have defined homes |
| ~~Infrastructure impact on Connect Care clinical ops~~ (retired) | A9, A10, OPS2 | *Resolved by assumption — instance scaled for ~100,000 users; VIMS load is marginal* | N/A — scaling assumption accepted | None | **Closed.** Residual is licensing for added named users + batch/portal path throughput, not instance capacity |
| Cold chain incident guided workflow | B8, A6 | Inconsistent documentation/handling of breaches | Internal: Epic workflow build (branching prompts, forced docs). External: **portal guided forms** (portal scope expansion) | Epic: Medium · Portal: Low–Medium | **Low–Medium** |
| Batch data processing pipeline | B3 | No operational bulk-load with validation/error queues | Custom ETL + error UI + monitoring | High | **Medium** |
| GoA/PPHS UI-UX & WCAG compliance | UX2 | Mandatory UI standard unmet by core Epic UI | External portal built to standard; core Willow UI cannot be reskinned | High (portal) | **Medium–High** — Epic UI remains non-compliant |
| Bandwidth performance ≤10 Mbps | UE-02 | Rural/pharmacy performance unproven for heavy workflows | Portal designed for low bandwidth; Epic benchmark for HyperDrive | ⚠ Confirm | **Medium** |
| Forecast-based ordering / demand modelling | C9, D8, D9, D10 | No predictive allocation/demand planning. Data foundation improved June 11, 2026 — actual external on-hand/consumption now captured in Willow | Third-party analytics integration over Willow data | Major Enhancement | **Low** — desirable, not mandatory |
| **External on-hand data quality & reporting cadence** (new June 11, 2026) | D1, B2, A8, C5, C8 | Portal-reported counts are only as current and accurate as provider reporting behaviour; PIM Guide warns inaccurate inbound feeds drive increased cycle counts (pp. 13–14). Physician clinics report manually | Reporting-cadence rules (e.g., count required at ordering), compliance monitoring/reporting, ZPM-16 count messages as remote cycle counts, periodic forced recounts | Medium (governance + portal UX) | **Medium** — operational/behavioural risk, not technical |
| **Portal concentration / delivery risk** (new June 11, 2026) | A2, A4, A6, A7, A8, B8, C1–C8, D5, F10, UX2 | The portal scope expansion moves many requirements out of Epic custom development and into a single custom application: ordering, approvals, thresholds, exception capture, recall execution, pull-back, guided returns, cold-chain capture, on-hand reporting, **all external notifications**. The portal becomes mission-critical infrastructure — single point of delivery and operational failure for the entire external tier (~1,500 sites) | Treat the portal as a formal product: dedicated delivery team, phased releases (ordering/on-hand first; recall/approvals next), HA hosting, support model, GoA/PPHS-compliant build (also resolves UX2), notification-engine fallback (e.g., direct email) for outage scenarios | High (portal program — aggregate of split portal ratings) | **Medium** — risk is consolidated and manageable, but portal delivery now gates most external-tier requirements |

---

## Open Confirmation Items (carried from the Gap Assessment)

These are the rows above flagged **⚠ Confirm with Epic**, consolidated:

1. **GHX XML schema + minimum job interval** for Batch Scheduler template 48016 (parent SLG 3992958) — gates A4, C1.
2. **Interconnect API surface** for order-status-by-ID reads and real-time SupplyRequest creation (urgent path) — gates C3; C8 narrowed June 11, 2026 to portal *display* of Willow balances (data path now via ADS feed).
3. **SupplyRequest / SupplyDelivery write support** in Willow via FHIR — gates F4 and the whole external write path.
4. ~~**Connect Care infrastructure isolation & capacity headroom** for peak VIMS load~~ — **retired** per the scaling assumption (instance provisioned for ~100,000 users). Remaining item is confirming **licensing for the added named users**, not capacity.
5. ~~**Canadian hosting / data residency** confirmation for VIMS data and DR~~ — **resolved June 11, 2026**: HSS hosts its own Epic instance in Alberta data centres, satisfying G4/G5 and the Canadian DR facility condition of G8. Remaining item is DR plan documentation/testing cadence, not hosting location.
6. **Canadian X12 EDI requirements** (DIN vs NDC, trading-partner setup) for PVD→supplier ordering — gates E2 and outbound PO.
7. **Reference implementation** of an external portal authenticating as provider-portal users submitting Willow supply orders — gates CR-01/CR-04 evidence.
8. **≤10 Mbps performance benchmarks** for HyperDrive inventory workflows — gates UE-02/OPS2.
9. **Cogito predictive/analytics scope** vs. required third-party tools — gates D2, D9.
10. **ADS load/unload interface with a non-ADS source** (added June 11, 2026): supportability and licensing of the portal back end emulating a medication cabinet (HL7 ZPM messages) to maintain external location balances (PIM Guide pp. 84–86) — gates D1, A4 receipt confirmation, C8, A8.
11. **Lot/expiry granularity in ZPM messages** (added June 11, 2026): whether the ADS interface persists lot and expiry to balances at external locations — gates B2, D3, and the A7/D5 recall-identification upgrade.
12. **Hold-location auto-transfer with an emulated ADS** (added June 11, 2026): whether designating the depot as inventory hold location triggers depot→site auto-transfer on a portal-originated "load" message (PIM Guide pp. 31–32) — gates native A4 receipt confirmation.
13. **Rebalance Stock scope across external inventory locations** (added June 11, 2026) — gates the A8 visibility upgrade.
14. **Outbound event/extract mechanism to drive the portal notification engine** (added June 11, 2026 — portal scope expansion): how shipment, low-stock, and near-expiry events reach the portal (HL7/Bridges push, scheduled Cogito extract, or Interconnect polling), and at what latency — gates C4, C7, and recall-notification timing (A7).
15. **GHX XML (template 48016) field capacity for reason codes / approval metadata** (added June 11, 2026): whether exception justifications and approval identifiers captured in the portal can be carried on the imported order, or remain portal-side only — affects C6 auditability within Willow.

---

*Sources: [[Epic Willow Gap Assessment - Alberta Instance Extension]]; [[Epic Willow Inventory Assessment Package]]; [[SBAR - Epic Willow Extension for Provincial Vaccine Depot]]; [[VIMS RFP Detailed Requirements]]; Willow Inventory X12 Interface Setup and Support Guide (Epic, May 2, 2025); Pharmacy Inventory Management Setup and Support Guide (Epic, May 1, 2026).*
