- Employees
	- Triage Nurse
	- Emergency Physician
	- Admission Clerk
	- Protective Services
	- Finance
- Partners
	- Emergency Medical Services
	- First Responders
	- Primary Care
	- Continuing Care
	- Inter-facility Transport
- Payors
	- Insurance
	- Financial Institutions
- Regulators
	- Communicable Disease
	- 
- Internal Value Stream Network
	- Pharmacy
	- Imaging
	- Inpatient
	- Specialist Consult
	- Laboratory
	- Housekeeping
	- Porter Services

